version: '3.9'

services:
  db:
    image: postgres:16.0
    env_file: server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: restaurant_website
    env_file: server/.env
    build:
      context: ./server
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "5000:5000"

  migrate:
    image: restaurant_website
    env_file: server/.env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 5 && npx prisma migrate deploy"
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  postgres_data: